general {
    lock_cmd = pgrep -f 'quickshell.*Lock\.qml' >/dev/null || ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session; sleep 1
    after_sleep_cmd = ~/.config/hypr/scripts/suspend.sh resume
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 120
    on-timeout = hyprctl eval "hl.dispatch(hl.dsp.dpms({action='off'}))"
    on-resume = hyprctl eval "hl.dispatch(hl.dsp.dpms({action='on'}))"
}

listener {
    timeout = 180 # 3 minutes
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1800 # 30 minutes of idle inactivity
    on-timeout = systemctl suspend
}