general {
    lock_cmd = pgrep -f 'quickshell.*Lock\.qml' >/dev/null || ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl eval "hl.dispatch(hl.dsp.dpms({action='on'}))"
}

listener {
    timeout = 120
    on-timeout = hyprctl eval "hl.dispatch(hl.dsp.dpms({action='off'}))"
    on-resume = hyprctl eval "hl.dispatch(hl.dsp.dpms({action='on'}))"
}

listener {
    timeout = 150
    on-timeout = loginctl lock-session
}


# listener {
#     timeout = 10000
#     on-timeout = systemctl suspend
# }