source = env.conf
source = startup.conf
source = keybinds.conf
source = rules.conf
source = input.conf
source = appearance.conf
source = layout.conf
source = misc.conf

monitor=,preferred,auto,auto,bitdepth,10

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]














### WINDOWS AND WORKSPACES ###

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
