-- Generated by nwg-displays on 2026-07-31 at 19:50:40. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1620@60.0",
    position = "0x0",
    scale = 2.0,
    bitdepth = 10
})
