plugin {
    hyprexpo {
        columns = 3
        gaps_in = 5
        gaps_out = 0
        bg_col = rgb(111111)
        workspace_method = center current
        show_cursor = 1
        show_pinned_windows = 0
        keynav_enable = 1
    }
}
bind = $mainMod, TAB, hyprexpo:expo, toggle