layerrule = noanim, slurp
layerrule = noanim, selection

## Picture-in-Picture
#windowrule = float,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = pin,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = size 25% 25%,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = move 73% 72%,title:^(.*[Pp]icture.*[Pp]icture.*)$

# Quickshell layers
#layerrule = blur true,match:namespace quickshell-launcher
#layerrule = ignore_alpha 0,match:namespace quickshell-launcher

#layerrule = blur true,match:namespace quickshell-notifications
#layerrule = ignore_alpha 0,match:namespace quickshell-notifications

#layerrule = blur true,match:namespace quickshell-control-center
#layerrule = ignore_alpha 0,match:namespace quickshell-control-center
