# Bluetooth
windowrule = match:class ^(\.blueman-manager-wrapped)$, float on
windowrule = match:class ^(\.blueman-manager-wrapped)$, center on
windowrule = match:class ^(\.blueman-manager-wrapped)$, size 700 500
# windowrule = match:class ^(\.blueman-manager-wrapped)$, pin on

# Pipewire Volume Control
windowrule = match:class ^(com\.saivert\.pwvucontrol)$, float on
windowrule = match:class ^(com\.saivert\.pwvucontrol)$, center on
windowrule = match:class ^(com\.saivert\.pwvucontrol)$, size 900 600
# windowrule = match:class ^(com\.saivert\.pwvucontrol)$, pin on

# Picture-in-Picture
windowrule = float, title:^(Picture.*Picture)$
windowrule = pin, title:^(Picture.*Picture)$
windowrule = stayfocused, title:^(Picture.*Picture)$
windowrule = size 640 360, title:^(Picture.*Picture)$
windowrule = move 100%-660 40, title:^(Picture.*Picture)$

## Picture-in-Picture
#windowrule = float,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = pin,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = size 25% 25%,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = move 73% 72%,title:^(.*[Pp]icture.*[Pp]icture.*)$

# Quickshell layers
#layerrule = blur true,match:namespace quickshell-launcher
#layerrule = ignore_alpha 0,match:namespace quickshell-launcher

#layerrule = blur true,match:namespace quickshell-notifications
#layerrule = ignore_alpha 0,match:namespace quickshell-notifications

#layerrule = blur true,match:namespace quickshell-control-center
#layerrule = ignore_alpha 0,match:namespace quickshell-control-center

