windowrule = opaque true, match:class zen
windowrule = opaque true, match:class ^mpv
windowrule = opaque true, match:class ^Spotify
windowrule = opaque true, match:class ^brave-browser
# windowrule = opaque true, match:class ^org.kde.okular 

windowrule = opacity 0.6, match:class ^org.wezfurlong.wezterm
windowrule = opacity 0.8, match:class ^codium
# windowrule = opacity 0.83, match:class ^org.kde.dolphin

windowrule = opacity 0.65, match:class brave-chat.openai.com__-Default #chatgpt
windowrule = opacity 0.8, match:class brave-gemini.google.com__app-Default #gemini
windowrule = opacity 0.78, match:class brave-claude.ai__new-Default #claude
# windowrule = opacity 0.55, match:class brave-monkeytype.com__-Default #monkeytype
windowrule = opacity 0.8, match:class brave-www.notion.so__02917993852a4825ab25a38c938de4f8-Default#notion
# windowrule = opaque true, match:class ^chrome-agimnkijcaahngcdmfeangaknmldooml-Default$ #youtube
# windowrule = opaque true, match:class ^chrome-mpnpojknpmmopombnjdcgaaiekajbnjb-Default$ #docs
# windowrule = opaque true, match:class ^chrome-fhihpiojkbmbpdjeoajapmgkhlnakfjf-Default$ #sheets
# windowrule = opacity 0.6, match:class ^chrome-pcklphganfmjgkefaemldhkgjhicbied-Default$ #keybr

windowrule = opaque true, match:title ^Picture in picture$


# Bluetooth
windowrule = match:class ^(\.blueman-manager-wrapped)$, float on
windowrule = match:class ^(\.blueman-manager-wrapped)$, center on
windowrule = match:class ^(\.blueman-manager-wrapped)$, size 700 500
# windowrule = match:class ^(\.blueman-manager-wrapped)$, pin on

# Pipewire Volume Control
windowrule = match:class ^(com\.saivert\.pwvucontrol)$, float on
windowrule = match:class ^(com\.saivert\.pwvucontrol)$, center on
windowrule = match:class ^(com\.saivert\.pwvucontrol)$, size 900 600
# windowrule = match:class ^(com\.saivert\.pwvucontrol)$, pin on

# Picture-in-Picture
windowrule = match:title ^Picture\ in\ picture$, float on
windowrule = match:title ^Picture\ in\ picture$, pin on
windowrule = match:title ^Picture\ in\ picture$, size 20% 20%


# ==========================
# Quickshell
# ==========================

windowrule = match:title ^(app-launcher)$, float on
windowrule = match:title ^(app-launcher)$, center on
windowrule = match:title ^(app-launcher)$, size 1200 600

# Rofi Menu Blur and Glass Architecture
layerrule = match:namespace ^(rofi)$, blur on
layerrule = match:namespace ^(rofi)$, ignore_alpha 0.1
# Force Rofi to slide in smoothly from the left screen boundary
layerrule = match:namespace ^(rofi)$, animation slide left

# ==========================
# CS2
# ==========================

# windowrule = match:class ^(cs2)$, immediate on
# windowrule = match:class ^(cs2)$, keepaspectratio on

## Picture-in-Picture
#windowrule = float,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = pin,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = size 25% 25%,title:^(.*[Pp]icture.*[Pp]icture.*)$
#windowrule = move 73% 72%,title:^(.*[Pp]icture.*[Pp]icture.*)$

# Quickshell layers
#layerrule = blur true,match:namespace quickshell-launcher
#layerrule = ignore_alpha 0,match:namespace quickshell-launcher

#layerrule = blur true,match:namespace quickshell-notifications
#layerrule = ignore_alpha 0,match:namespace quickshell-notifications

#layerrule = blur true,match:namespace quickshell-control-center
#layerrule = ignore_alpha 0,match:namespace quickshell-control-center

