# Wallpaper
exec-once = ~/.config/hypr/scripts/wallpaper_daemon.sh

# Idle
exec-once = hypridle

# Media daemon
exec-once = playerctld

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Easyeffects
exec-once = systemctl --user start easyeffects

# Quickshell
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml


# Optional (enable later)
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py