# Wallpaper
exec-once = awww-daemon

# Idle
exec-once = hypridle

# Media daemon
exec-once = playerctld

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Easyeffects
exec-once = systemctl --user start easyeffects

# Cursor
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'ArcMidnight-Cursors'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

# Quickshell
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml


# Optional (enable later)
exec-once = ~/.config/quickshell/scripts/volume_listener.sh
exec-once = python3 ~/.config/quickshell/focustime/focus_daemon.py